version: "3.9"

services:
  db:
    image: postgres
    container_name: expensetracker_db
    restart: always
    environment:
      POSTGRES_DB: expensetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: expensetracker_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expensetracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: "U9jM3LrT5pQsAxV8NnBxWz2KyReGvHdQ"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: expensetracker_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
